/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.GUI;

import br.ufrn.controlers.UpdateWeather;
import br.ufrn.controlers.ConcreteUpdateWeather;
import javax.swing.plaf.SliderUI;

/**
 *
 * @author Edilvo
 */
public class Sensores extends javax.swing.JFrame {

    random setaValores;
    

    /**
     * Creates new form Sensores
     */
    public Sensores() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SliderPolA1 = new javax.swing.JSlider();
        SliderFluxA1 = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        SliderPolA2 = new javax.swing.JSlider();
        SliderFluxA2 = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        SliderPolA3 = new javax.swing.JSlider();
        SliderFluxA3 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("AREA 1"));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 300));

        SliderPolA1.setMajorTickSpacing(20);
        SliderPolA1.setMaximum(120);
        SliderPolA1.setMinorTickSpacing(10);
        SliderPolA1.setPaintLabels(true);
        SliderPolA1.setPaintTicks(true);
        SliderPolA1.setSnapToTicks(true);
        SliderPolA1.setBorder(javax.swing.BorderFactory.createTitledBorder("Indice de poluição"));
        SliderPolA1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderPolA1StateChanged(evt);
            }
        });

        SliderFluxA1.setMajorTickSpacing(20);
        SliderFluxA1.setMinorTickSpacing(10);
        SliderFluxA1.setPaintLabels(true);
        SliderFluxA1.setPaintTicks(true);
        SliderFluxA1.setSnapToTicks(true);
        SliderFluxA1.setToolTipText("");
        SliderFluxA1.setValue(70);
        SliderFluxA1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fluxo de veículos (veículos por min.)"));
        SliderFluxA1.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderFluxA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SliderPolA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(SliderPolA1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SliderFluxA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(829, 829, 829))
        );

        SliderPolA1.getAccessibleContext().setAccessibleName("Temperatura 1");
        SliderPolA1.getAccessibleContext().setAccessibleDescription("");
        SliderFluxA1.getAccessibleContext().setAccessibleName("Humidade 1");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("AREA 2"));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 300));

        SliderPolA2.setMajorTickSpacing(20);
        SliderPolA2.setMaximum(120);
        SliderPolA2.setMinorTickSpacing(10);
        SliderPolA2.setPaintLabels(true);
        SliderPolA2.setPaintTicks(true);
        SliderPolA2.setToolTipText("Temperatura 2");
        SliderPolA2.setValue(25);
        SliderPolA2.setBorder(javax.swing.BorderFactory.createTitledBorder("Indice de poluição"));
        SliderPolA2.setName("Temperatura 2"); // NOI18N
        SliderPolA2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderPolA2StateChanged(evt);
            }
        });

        SliderFluxA2.setMajorTickSpacing(20);
        SliderFluxA2.setMinorTickSpacing(10);
        SliderFluxA2.setPaintLabels(true);
        SliderFluxA2.setPaintTicks(true);
        SliderFluxA2.setToolTipText("");
        SliderFluxA2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fluxo de veículos (veículos por min.)"));
        SliderFluxA2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderFluxA2StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderPolA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SliderFluxA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(SliderPolA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SliderFluxA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(904, 904, 904))
        );

        SliderPolA2.getAccessibleContext().setAccessibleName("Temperatura 2");
        SliderFluxA2.getAccessibleContext().setAccessibleName("Humidade 2");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("AREA 3"));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 300));

        SliderPolA3.setMajorTickSpacing(20);
        SliderPolA3.setMaximum(120);
        SliderPolA3.setMinorTickSpacing(10);
        SliderPolA3.setPaintLabels(true);
        SliderPolA3.setPaintTicks(true);
        SliderPolA3.setValue(25);
        SliderPolA3.setBorder(javax.swing.BorderFactory.createTitledBorder("Indice de poluição"));
        SliderPolA3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderPolA3StateChanged(evt);
            }
        });

        SliderFluxA3.setMajorTickSpacing(20);
        SliderFluxA3.setMinorTickSpacing(10);
        SliderFluxA3.setPaintLabels(true);
        SliderFluxA3.setPaintTicks(true);
        SliderFluxA3.setToolTipText("");
        SliderFluxA3.setBorder(javax.swing.BorderFactory.createTitledBorder("Fluxo de veículos (veículos por min.)"));
        SliderFluxA3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderFluxA3StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderPolA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SliderFluxA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(SliderPolA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SliderFluxA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(544, 544, 544))
        );

        SliderPolA3.getAccessibleContext().setAccessibleName("Temperatura 3");
        SliderFluxA3.getAccessibleContext().setAccessibleName("Humidade 3");

        jButton1.setText("Randomizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(271, 271, 271))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    UpdateWeather atualizar = new ConcreteUpdateWeather();

    private void SliderPolA1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderPolA1StateChanged
        atualizar.updateWeather(SliderFluxA1.getValue(),
                                SliderFluxA2.getValue(),
                                SliderFluxA3.getValue(),
                                SliderPolA1.getValue(),
                                SliderPolA2.getValue(),
                                SliderPolA3.getValue());
    }//GEN-LAST:event_SliderPolA1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    }//GEN-LAST:event_jButton1ActionPerformed

    private void SliderFluxA2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderFluxA2StateChanged
         atualizar.updateWeather(SliderFluxA1.getValue(),
                                SliderFluxA2.getValue(),
                                SliderFluxA3.getValue(),
                                SliderPolA1.getValue(),
                                SliderPolA2.getValue(),
                                SliderPolA3.getValue());
    }//GEN-LAST:event_SliderFluxA2StateChanged

    private void SliderPolA2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderPolA2StateChanged
        atualizar.updateWeather(SliderFluxA1.getValue(),
                                SliderFluxA2.getValue(),
                                SliderFluxA3.getValue(),
                                SliderPolA1.getValue(),
                                SliderPolA2.getValue(),
                                SliderPolA3.getValue());
    }//GEN-LAST:event_SliderPolA2StateChanged

    private void SliderFluxA3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderFluxA3StateChanged
         atualizar.updateWeather(SliderFluxA1.getValue(),
                                SliderFluxA2.getValue(),
                                SliderFluxA3.getValue(),
                                SliderPolA1.getValue(),
                                SliderPolA2.getValue(),
                                SliderPolA3.getValue());
    }//GEN-LAST:event_SliderFluxA3StateChanged

    private void SliderPolA3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderPolA3StateChanged
        atualizar.updateWeather(SliderFluxA1.getValue(),
                                SliderFluxA2.getValue(),
                                SliderFluxA3.getValue(),
                                SliderPolA1.getValue(),
                                SliderPolA2.getValue(),
                                SliderPolA3.getValue());
    }//GEN-LAST:event_SliderPolA3StateChanged
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sensores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sensores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sensores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sensores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sensores().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider SliderFluxA1;
    private javax.swing.JSlider SliderFluxA2;
    private javax.swing.JSlider SliderFluxA3;
    private javax.swing.JSlider SliderPolA1;
    private javax.swing.JSlider SliderPolA2;
    private javax.swing.JSlider SliderPolA3;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
